import re


class FinancialExtractionService:

    PATTERNS = {
        "revenue": [
            r"(?:net sales|sales|total revenue|revenue)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "net_income": [
            r"(?:net income|net earnings|net profit)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "operating_income": [
            r"(?:operating income|income from operations)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "total_assets": [
            r"(?:total assets)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "total_liabilities": [
            r"(?:total liabilities)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "total_equity": [
            r"(?:total equity|total shareholders.? equity|shareholders.? equity|stockholders.? equity)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "cash": [
            r"(?:cash and cash equivalents|cash & cash equivalents|cash, cash equivalents and short-term investments|cash equivalents|cash)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "inventory": [
            r"(?:inventories|inventory)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "receivables": [
            r"(?:accounts receivable|trade receivables|receivables|net receivables)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "debt": [
            r"(?:total debt|long-term debt|long term debt|borrowings|debt)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "eps": [
            r"(?:earnings per share|basic eps|diluted eps|eps)\D{0,40}([\d,]+\.\d+|[\d,]+)",
        ],

        "operating_cash_flow": [
            r"(?:operating cash flow|cash generated by operating activities|net cash provided by operating activities)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "free_cash_flow": [
            r"(?:free cash flow)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],

        "shares_outstanding": [
            r"(?:shares outstanding|weighted average shares outstanding|common shares outstanding)\D{0,80}([\d,]+\.\d+|[\d,]+)",
        ],
    }

    @staticmethod
    def _to_number(value: str):
        try:
            return float(value.replace(",", ""))
        except Exception:
            return None

    @classmethod
    def _extract_value(
        cls,
        text: str,
        field: str,
        patterns: list[str],
    ):

        matches = []

        for pattern in patterns:

            results = re.findall(
                pattern,
                text,
                flags=re.IGNORECASE | re.MULTILINE,
            )

            matches.extend(results)

        numbers = []

        for match in matches:

            value = cls._to_number(match)

            if value is not None:
                numbers.append(value)

        if not numbers:
            return None

        # EPS is normally a small decimal value.
        if field == "eps":

            decimals = [
                value
                for value in numbers
                if value < 1000
            ]

            if decimals:
                return max(decimals)

        # Shares Outstanding is normally the largest number.
        if field == "shares_outstanding":
            return max(numbers)

        # Monetary values usually use the largest figure.
        return max(numbers)

    @classmethod
    def extract(cls, text: str):

        results = {}

        for field, patterns in cls.PATTERNS.items():

            results[field] = cls._extract_value(
                text,
                field,
                patterns,
            )

        return results