"""phase2_initial_schema

Revision ID: 250e0245f1b1
Revises: 
Create Date: 2026-06-23 13:43:50.063534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250e0245f1b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='user_role'), server_default='ANALYST', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('idx_companies_name_fts', 'companies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_companies_sector', 'companies', ['sector'], unique=False)
    op.create_index('idx_companies_ticker', 'companies', ['ticker'], unique=False, postgresql_where='is_deleted = false')
    op.create_table('filings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filing_type', sa.Enum('ANNUAL_REPORT', 'FORM_10K', 'FORM_10Q', 'BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', name='filing_type'), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=10), server_default='FY', nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'EXTRACTING', 'EXTRACTED', 'NLP_PROCESSING', 'NLP_COMPLETE', 'EMBEDDING', 'INDEXED', 'ANALYZING', 'ANALYZED', 'COMPLETE', 'FAILED', name='processing_status'), server_default='PENDING', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_period', 'filing_type', name='uq_filing_per_company_year_period_type')
    )
    op.create_index('idx_filings_company_id', 'filings', ['company_id'], unique=False)
    op.create_index('idx_filings_created_at', 'filings', ['created_at'], unique=False)
    op.create_index('idx_filings_fiscal_year', 'filings', ['company_id', 'fiscal_year'], unique=False)
    op.create_index('idx_filings_status', 'filings', ['processing_status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_filing', 'chat_sessions', ['filing_id'], unique=False)
    op.create_index('idx_chat_sessions_updated', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.Enum('COVER', 'MD_AND_A', 'RISK_FACTORS', 'FINANCIAL_STATEMENTS', 'NOTES_TO_FINANCIALS', 'AUDITOR_REPORT', 'APPENDIX', 'UNKNOWN', name='section_type'), server_default='UNKNOWN', nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'chunk_index', name='uq_chunk_index_per_filing')
    )
    op.create_index('idx_chunks_filing_id', 'document_chunks', ['filing_id'], unique=False)
    op.create_index('idx_chunks_not_embedded', 'document_chunks', ['is_embedded'], unique=False, postgresql_where='is_embedded = false')
    op.create_index('idx_chunks_page', 'document_chunks', ['filing_id', 'page_number'], unique=False)
    op.create_index('idx_chunks_section', 'document_chunks', ['filing_id', 'section_type'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('ratio_category', sa.Enum('LIQUIDITY', 'PROFITABILITY', 'LEVERAGE', 'EFFICIENCY', 'MARKET', name='ratio_category'), nullable=False),
    sa.Column('ratio_name', sa.String(length=100), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('computed_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('benchmark_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('benchmark_source', sa.String(length=255), nullable=True),
    sa.Column('signal', sa.Enum('GOOD', 'WARNING', 'CRITICAL', 'NEUTRAL', name='ratio_signal'), server_default='NEUTRAL', nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'ratio_name', name='uq_ratio_name_per_filing')
    )
    op.create_index('idx_ratios_category', 'financial_ratios', ['filing_id', 'ratio_category'], unique=False)
    op.create_index('idx_ratios_filing_id', 'financial_ratios', ['filing_id'], unique=False)
    op.create_index('idx_ratios_signal', 'financial_ratios', ['signal'], unique=False)
    op.create_table('financial_statements',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('statement_type', sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW_STATEMENT', name='statement_type'), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('unit_multiplier', sa.Integer(), server_default='1', nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'statement_type', name='uq_statement_type_per_filing')
    )
    op.create_index('idx_statements_filing_id', 'financial_statements', ['filing_id'], unique=False)
    op.create_index('idx_statements_normalized_gin', 'financial_statements', ['normalized_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_statements_type', 'financial_statements', ['statement_type'], unique=False)
    op.create_table('forecasts',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.Enum('REVENUE', 'NET_PROFIT', 'EBITDA', 'OPERATING_CASH_FLOW', name='forecast_metric'), nullable=False),
    sa.Column('model_used', sa.Enum('PROPHET', 'ARIMA', name='forecast_model'), nullable=False),
    sa.Column('historical_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_points_count', sa.Integer(), nullable=False),
    sa.Column('forecast_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forecast_years', sa.Integer(), server_default='3', nullable=False),
    sa.Column('model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mae', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('growth_rate_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'metric_name', 'model_used', name='uq_forecast_per_filing_metric_model')
    )
    op.create_index('idx_forecasts_data_gin', 'forecasts', ['forecast_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_forecasts_filing_id', 'forecasts', ['filing_id'], unique=False)
    op.create_index('idx_forecasts_metric', 'forecasts', ['metric_name'], unique=False)
    op.create_table('fraud_assessments',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('dsri', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('gmi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('aqi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sgi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('depi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sgai', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('lvgi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tata', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beneish_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beneish_signal', sa.Enum('SAFE', 'GREY_ZONE', 'MANIPULATOR', name='fraud_risk_class'), nullable=True),
    sa.Column('altman_x1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_x2', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_x3', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_x4', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_x5', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('altman_zone', sa.Enum('SAFE', 'GREY', 'DISTRESS', name='altman_zone'), nullable=True),
    sa.Column('isolation_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('overall_fraud_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fraud_risk_class', sa.Enum('SAFE', 'GREY_ZONE', 'MANIPULATOR', name='fraud_risk_class'), server_default='SAFE', nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', name='uq_fraud_assessment_per_filing')
    )
    op.create_index('idx_fraud_beneish_signal', 'fraud_assessments', ['beneish_signal'], unique=False)
    op.create_index('idx_fraud_filing_id', 'fraud_assessments', ['filing_id'], unique=False)
    op.create_index('idx_fraud_red_flags_gin', 'fraud_assessments', ['red_flags'], unique=False, postgresql_using='gin')
    op.create_index('idx_fraud_risk_class', 'fraud_assessments', ['fraud_risk_class'], unique=False)
    op.create_table('generated_reports',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), server_default='EXECUTIVE_PDF', nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('included_sections', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('generation_status', sa.String(length=50), server_default='PENDING', nullable=False),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_filing_id', 'generated_reports', ['filing_id'], unique=False)
    op.create_index('idx_reports_user_id', 'generated_reports', ['user_id'], unique=False)
    op.create_table('nlp_insights',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment_label'), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('sentiment_section', sa.String(length=100), nullable=True),
    sa.Column('sentiment_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_sentence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('high_risk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('overall_tone', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment_label'), nullable=True),
    sa.Column('tone_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', name='uq_nlp_insight_per_filing')
    )
    op.create_index('idx_nlp_entities_gin', 'nlp_insights', ['entities'], unique=False, postgresql_using='gin')
    op.create_index('idx_nlp_filing_id', 'nlp_insights', ['filing_id'], unique=False)
    op.create_index('idx_nlp_risk_sentences_gin', 'nlp_insights', ['risk_sentences'], unique=False, postgresql_using='gin')
    op.create_index('idx_nlp_sentiment', 'nlp_insights', ['sentiment_label'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_class', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_class'), nullable=False),
    sa.Column('xgb_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('lgbm_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('xgb_weight', sa.Numeric(precision=4, scale=3), server_default='0.6', nullable=False),
    sa.Column('lgbm_weight', sa.Numeric(precision=4, scale=3), server_default='0.4', nullable=False),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_base_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lime_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('narrative_model', sa.String(length=100), server_default='llama3', nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', name='uq_risk_prediction_per_filing')
    )
    op.create_index('idx_risk_class', 'risk_predictions', ['risk_class'], unique=False)
    op.create_index('idx_risk_filing_id', 'risk_predictions', ['filing_id'], unique=False)
    op.create_index('idx_risk_score_desc', 'risk_predictions', ['risk_score'], unique=False)
    op.create_index('idx_risk_shap_gin', 'risk_predictions', ['shap_values'], unique=False, postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('retrieval_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_role', 'chat_messages', ['session_id', 'role'], unique=False)
    op.create_index('idx_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_session', table_name='chat_messages')
    op.drop_index('idx_messages_role', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_risk_shap_gin', table_name='risk_predictions', postgresql_using='gin')
    op.drop_index('idx_risk_score_desc', table_name='risk_predictions')
    op.drop_index('idx_risk_filing_id', table_name='risk_predictions')
    op.drop_index('idx_risk_class', table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index('idx_nlp_sentiment', table_name='nlp_insights')
    op.drop_index('idx_nlp_risk_sentences_gin', table_name='nlp_insights', postgresql_using='gin')
    op.drop_index('idx_nlp_filing_id', table_name='nlp_insights')
    op.drop_index('idx_nlp_entities_gin', table_name='nlp_insights', postgresql_using='gin')
    op.drop_table('nlp_insights')
    op.drop_index('idx_reports_user_id', table_name='generated_reports')
    op.drop_index('idx_reports_filing_id', table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('idx_fraud_risk_class', table_name='fraud_assessments')
    op.drop_index('idx_fraud_red_flags_gin', table_name='fraud_assessments', postgresql_using='gin')
    op.drop_index('idx_fraud_filing_id', table_name='fraud_assessments')
    op.drop_index('idx_fraud_beneish_signal', table_name='fraud_assessments')
    op.drop_table('fraud_assessments')
    op.drop_index('idx_forecasts_metric', table_name='forecasts')
    op.drop_index('idx_forecasts_filing_id', table_name='forecasts')
    op.drop_index('idx_forecasts_data_gin', table_name='forecasts', postgresql_using='gin')
    op.drop_table('forecasts')
    op.drop_index('idx_statements_type', table_name='financial_statements')
    op.drop_index('idx_statements_normalized_gin', table_name='financial_statements', postgresql_using='gin')
    op.drop_index('idx_statements_filing_id', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('idx_ratios_signal', table_name='financial_ratios')
    op.drop_index('idx_ratios_filing_id', table_name='financial_ratios')
    op.drop_index('idx_ratios_category', table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index('idx_chunks_section', table_name='document_chunks')
    op.drop_index('idx_chunks_page', table_name='document_chunks')
    op.drop_index('idx_chunks_not_embedded', table_name='document_chunks', postgresql_where='is_embedded = false')
    op.drop_index('idx_chunks_filing_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_filing', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_filings_status', table_name='filings')
    op.drop_index('idx_filings_fiscal_year', table_name='filings')
    op.drop_index('idx_filings_created_at', table_name='filings')
    op.drop_index('idx_filings_company_id', table_name='filings')
    op.drop_table('filings')
    op.drop_index('idx_companies_ticker', table_name='companies', postgresql_where='is_deleted = false')
    op.drop_index('idx_companies_sector', table_name='companies')
    op.drop_index('idx_companies_name_fts', table_name='companies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
